apiVersion: apps/v1
kind: Deployment
metadata:
  name: janitorr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: janitorr
  template:
    metadata:
      labels:
        app: janitorr
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      containers:
        - name: janitorr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: THC_PATH
              value: {{ .Values.env.THC_PATH | quote }}
            - name: THC_PORT
              value: {{ .Values.env.THC_PORT | quote }}
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: /workspace/application.yml
              subPath: application.yml
            {{- end }}
            {{- if .Values.persistence.logs.enabled }}
            - name: logs
              mountPath: /logs
            {{- end }}
            {{- if .Values.persistence.media.enabled }}
            - name: media
              mountPath: /data
            {{- end }}
          {{- if .Values.healthcheck.enabled }}
          startupProbe:
            exec:
              command: {{ toJson .Values.healthcheck.command }}
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
          {{- end }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.config.existingClaim }}{{ .Values.persistence.config.existingClaim }}{{ else }}janitorr-config{{ end }}
        {{- end }}
        {{- if .Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.logs.existingClaim }}{{ .Values.persistence.logs.existingClaim }}{{ else }}janitorr-logs{{ end }}
        {{- end }}
        {{- if .Values.persistence.media.enabled }}
        - name: media
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.media.existingClaim }}{{ .Values.persistence.media.existingClaim }}{{ else }}janitorr-media{{ end }}
        {{- end }}
