apiVersion: v2
name: transmission
description: Transmission bittorrent client Helm Chart
type: application
version: 1.4.2
appVersion: "1.4.2"
dependencies:
  - name: common
    repository: https://ryuunosukeds3.github.io/helm-charts
    version: 0.1.0
maintainers:
  - name: RyuunosukeDS3
    email: camelimsaturado@outlook.com
    url: https://github.com/ryuunosukeds3