image: "lscr.io/linuxserver/transmission:4.0.4@sha256:760b2d364dbfb6d84c9688f624dc48f98665b15e9e41be2170715afcc525e329"
replicaCount: 1

ingress:
  enabled: true
  hostname: transmission.local
  path: /
  pathType: Prefix
  backend:
    servicePort: http

containerPorts:
  http: 9091
  peer: 51413

service:
  type: ClusterIP
  nodePorts: {}
  # Uncomment to use nodePorts for specific ports
  # http: 9091
  # peer: 51413
  ports:
    http: 9091
    peer: 51413

livenessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistence:
  enabled: false

config:
  useSecret: true
  
  # Configuration settings, used if useSecret is false
  # settings: 
  #   download-dir: "/downloads/complete"
  #   incomplete-dir: "/downloads/inclopete"
  
  # Base64-encoded JSON settings for use with the Secret (if useSecret is true)
  secretSettings: eyJkb3dubG9hZC1kaXIiOiIvZG93bG9hZHMvY29tcGxldGUiLCJpbmNvbXBsZXRlLWRpciI6Ii9kb3dubG9hZHMvaW5jbG9wZXRlIn0=

env:
  # Example environment variables
  # Uncomment and set environment variables as needed
  # PUID: 1000
  # PGID: 1000
