image: "lscr.io/linuxserver/transmission:4.0.4@sha256:760b2d364dbfb6d84c9688f624dc48f98665b15e9e41be2170715afcc525e329"
replicaCount: 1

ingress:
  enabled: true
  hostname: transmission.local
  path: /
  pathType: Prefix
  backend:
    servicePort: http

containerPorts:
  http: 9091
  peer: 51413

service:
  type: ClusterIP
  nodePorts: {}
  # Uncomment to use nodePorts for specific ports
  # http: 9091
  # peer: 51413
  ports:
    http: 9091
    peer: 51413

livenessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistence:
  enabled: false

  # Example configuration for downloads PVC
  # downloads:
  #   size: 10Gi
  #   storageClass: "your-pv-storage-class"
  #   accessModes:
  #     - ReadWriteOnce

  # Example configuration for config PVC
  # config:
  #   size: 5Gi
  #   storageClass: "your-pv-storage-class"
  #   accessModes:
  #     - ReadWriteOnce

config:
  secret: true
  # Configuration settings, used if secret is false
  settings: {}
  #   {
  #     "download-dir": "/downloads/complete"
  #     "incomplete-dir": "/downloads/incomplete"
  #   }

env:
  # Example environment variables
  # Uncomment and set environment variables as needed
  # PUID: 1000
  # PGID: 1000

auth:
  enabled: true
  useExistingSecret: false  # Set to true to use an existing secret
  # existingSecretName: "existing-auth-secret"
  user: username
  password: secret-pass