apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nadekobot-pvc
  {{- if not .Values.persistence.enabled }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}