{{- if not .Values.secret.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: nadekobot-secret
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}