{{- if .Values.argo.token.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-argocd-token" .Release.Name }}
type: Opaque
stringData:
  token: {{ .Values.argo.token.tokenValue | quote }}
{{- end }}
