apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ARGOCD_URL
              value: "{{ .Values.argo.url }}"
{{- if .Values.argo.token.createSecret }}
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-argocd-token" .Release.Name }}
                  key: token
{{- else if .Values.argo.token.existingSecretName }}
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argo.token.existingSecretName }}
                  key: {{ .Values.argo.token.existingSecretKey | default "token" }}
{{- else }}
            # ARGOCD_TOKEN not set
{{- end }}
