{{- if .Values.config.settings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-conf"
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  read_only_settings.json: {{ toJson .Values.config.settings | quote }}
{{- end }}
