apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      initContainers:
        - name: update-settings
          image: python:3.9
          command: ["python", "/scripts/update_settings.py"]
          args:
            - echo -n "$(echo "$AUTH_USER" | sed 's/[\r\n]*$//')" > /env-vars/USER
            - echo -n "$(echo "$AUTH_PASS" | sed 's/[\r\n]*$//')" > /env-vars/PASS
          env:
            {{- if .Values.auth.enabled }}
            - name: AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.auth.useExistingSecret }}{{ .Values.auth.existingSecretName }}{{ else }}auth-secret{{ end }}
                  key: USER
            - name: AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.auth.useExistingSecret }}{{ .Values.auth.existingSecretName }}{{ else }}auth-secret{{ end }}
                  key: PASS
            {{- end }}
          volumeMounts:
            - name: script
              mountPath: /scripts
            - name: read-only-settings
              mountPath: /config/read_only_settings.json
              subPath: read_only_settings.json
            {{- if .Values.persistence.config }}
            - name: config-volume
              mountPath: /config
            {{- end }}
      containers:
        - name: transmission
          image: {{ .Values.image }}
          volumeMounts:
            {{- if .Values.persistence.downloads }}
            - name: transmission-downloads
              mountPath: /downloads
            {{- end }}
            {{- if .Values.persistence.config }}
            - name: config-volume
              mountPath: /config
            {{- end }}
          env:
            {{- if .Values.auth.enabled }}
            FILE__USER: /env-vars/USER
            FILE__PASS: /env-vars/PASS
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
      volumes:
        - name: script
          configMap:
            name: update-settings-script
        - name: read-only-settings
          configMap:
            name: "{{ .Release.Name }}-conf"
        {{- if .Values.persistence.downloads }}
        - name: transmission-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads-pvc
        {{- end }}
        {{- if .Values.persistence.config }}
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
        {{- end }}
