{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-downloads-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size }}
  storageClassName: {{ .Values.persistence.downloads.storageClass }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
{{- end }}
