{{- if and .Values.config.secret .Values.config.settings }}
apiVersion: v1
kind: Secret
metadata:
  name: read-only-settings-secret
  namespace: {{ .Release.Namespace | b64enc | quote }}
type: Opaque
data:
  read_only_settings.json: {{ .Values.config.settings | b64enc | quote }}
{{- end }}
---
{{- if values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: default
type: Opaque
data:
  USER: {{ .Values.auth.user | b64enc | quote }}
  PASS: {{ .Values.auth.password | b64enc | quote }}
{{- end }}