{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: default
type: Opaque
data:
  USER: {{ .Values.auth.user | b64enc | quote }}
  PASS: {{ .Values.auth.password | b64enc | quote }}
{{- end }}