{{- if and .Values.auth.enabled (not .Values.auth.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  USER: {{ .Values.auth.user | b64enc | quote }}
  PASS: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
