{{- if and (.Values.config.useSecret) .Values.config.secretSettings }}
apiVersion: v1
kind: Secret
metadata:
  name: read-only-settings-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  read_only_settings.json: {{ .Values.config.secretSettings | quote }}
{{- end }}
